use_accel: True
num_edits: 2
score_function: 'MaxMC' # choices=["MaxMC", "pvl"]
exploratory_grad_updates: False # False means we use Robust PLR
level_buffer_capacity: 10000
replay_prob: 0.8
staleness_coeff: 0.5
temperature: 2.0
topk_k: 4
minimum_fill_ratio: 0.5
prioritization: 'rank'
buffer_duplicate_check: False
accel_mutation: 'combined'