ALG_NAME: "ppo"
TOTAL_TIMESTEPS: null
LR: 0.0002
GAMMA: 0.97
VF_COEF: 0.5
CLIP_EPS: 0.3
NUM_ENVS: 64
NUM_STEPS: 32
ACTIVATION: "tanh"
GAE_LAMBDA: 0.9
LAYER_SIZE: 64
MAX_GRAD_NORM: 1
UPDATE_EPOCHS: 4
ENT_COEF: 0.05
NUM_MINIBATCHES: 16
ANNEAL_LR: True
DEBUG: False
SAVE_POLICY: False