ENV_NAME: "16-hosts-gen"
ENV_KWARGS:
  num_hosts: 16
  num_processes: 3
  num_services: 3
  num_os: 2
  num_subnets: 7
  topology_density: 0.15
  service_density: 0.7
  process_density: 0.7
  sensitive_density: 0.2
  distribute_homogeneous: True
  step_limit: 300
  scan_cost: 1
  exploit_cost: 3
  privesc_cost: 3
EVAL_ENV_KWARGS:
  topology_density: 0.24
  service_density: 0.5
  process_density: 0.5
  sensitive_density: 0.2
AUG_OBS: True
FULLY_OBS: False
NORMALIZE_REWARD: True
eval_topology_densities: [0.06, 0.115, 0.15, 0.195, 0.24]